project_name: k8s-checksum-injector

builds:
  - id: k8s-checksum-injector
    main: ./cmd/k8s-checksum-injector
    binary: k8s-checksum-injector
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
